@startuml
class com.example.wetouriah.ViewHolderWarehouse {
~ TextView address
}
class com.example.wetouriah.ImageResponse {
- String requestPickupImages
+ String getRequestPickupImages()
+ void setRequestPickupImages(String)
}
class com.example.wetouriah.WareHouseItemAdmin {
~ String id
~ String cctv
+ String getId()
+ void setId(String)
+ String getImage()
+ void setImage(String)
+ String getAddress()
+ void setAddress(String)
+ String getVolume()
+ void setVolume(String)
+ String getCctv()
+ void setCctv(String)
+ String getArmed_response()
+ void setArmed_response(String)
+ String getFire_safety_and_management()
+ void setFire_safety_and_management(String)
+ String getParking_space()
+ void setParking_space(String)
+ String getIs_approved()
+ void setIs_approved(String)
+ String getOperating_hours()
+ void setOperating_hours(String)
+ String getWarehouse_owner()
+ void setWarehouse_owner(String)
}
class com.example.wetouriah.AdapterAllUsers {
~ Context context
~ List<UserItem> UserItems
- OnClickListener onClickListener
+ AllUsersViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(AllUsersViewHolder,int)
+ int getItemCount()
+ void updateUserStatus(String,String)
+ void setOnClickListener(OnClickListener)
}
interface com.example.wetouriah.AdapterAllUsers$OnClickListener {
~ void onClick(int,UserItem)
}
class com.example.wetouriah.WarehousePortal {
- DrawerLayout drawerLayout
- ActionBarDrawerToggle toggle
- NavigationView navigationView
- TabLayout tab_layout
- RelativeLayout lyAllUndelivered
~ EditText pickdateEditText
~ EditText recipient_name
~ Button btnAddPickRequest
- int year
~ FloatingActionButton mAddFab
~ RelativeLayout lyPickRequestList
~ ScrollView lyAddPickRequest
~ TextView headerUsername
~ TextView qPrice
- Handler handler
- Runnable runnable
+ {static} String NEXT_SCREEN
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
- void showToast(String)
- void Logout()
+ boolean onNavigationItemSelected(MenuItem)
+ void onBackPressed()
- void showDatePicker(EditText)
- void showTimePicker(EditText)
+ double mCalulatePrice(double,double,double)
- void startPeriodicApiCall()
- void createNotification()
}
class com.example.wetouriah.TrackParcel {
~ RelativeLayout lyLocations
~ CardView cardSearch
~ EditText txtID
~ Button btnSearch
# void onCreate(Bundle)
- void LoadLocations()
+ void onBackPressed()
}
class com.example.wetouriah.Deliver {
~ SharedPreferences sharedPreferences
~ int itemId
~ String role
- {static} int PICK_IMAGE_REQUEST
- LinearLayout layoutImages
- ArrayList<Uri> imageUris
- ImageView imageView
~ Button btn_add_more
~ RatingBar ratingBar
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
+ void submitForm(String)
# void onActivityResult(int,int,Intent)
+ void mDelivered(String)
+ void addRatig(String,String)
+ void setImagesAndARating(String)
+ void displayImagesAndrating(List<String>,int)
}
class com.example.wetouriah.PickUpRequestItem {
~ String id
~ String tracking_number
~ String customer
~ String request_time
~ String date_and_time_pickup
~ String recipient_name
~ String recipient_phone
~ String pickup_location
~ String dropoff_location
~ String volume
~ String weight
~ String price_to_pay
~ String images
~ String status
+ String getId()
+ void setId(String)
+ String getTracking_number()
+ void setTracking_number(String)
+ String getCustomer()
+ void setCustomer(String)
+ String getRequest_time()
+ void setRequest_time(String)
+ String getDate_and_time_pickup()
+ void setDate_and_time_pickup(String)
+ String getRecipient_name()
+ void setRecipient_name(String)
+ String getRecipient_phone()
+ void setRecipient_phone(String)
+ String getPickup_location()
+ void setPickup_location(String)
+ String getDropoff_location()
+ void setDropoff_location(String)
+ String getVolume()
+ void setVolume(String)
+ String getWeight()
+ void setWeight(String)
+ String getPrice_to_pay()
+ void setPrice_to_pay(String)
+ String getImages()
+ void setImages(String)
+ String getStatus()
+ void setStatus(String)
}
class com.example.wetouriah.Register {
- RelativeLayout lyUsernameAndPassword
- Button btnRolesNext
- ImageView imageView
- EditText email
- RadioGroup rgRoles
- String imagepath
- String role
# void onCreate(Bundle)
# void onActivityResult(int,int,Intent)
+ void SimpleAddUser(String,String,String,String,String,String,String,String,String)
+ void addUser(String,String,String,String,String,String,String,String,String,String,String)
+ void onBackPressed()
}
class com.example.wetouriah.AllCarsViewHolder {
~ CheckBox is_approved
~ TextView type
}
class com.example.wetouriah.Signature {
- int mDefaultColor
- {static} int REQUEST_CODE
~ Button btnSave
~ ImageView imgSignature
~ SignatureView signature_view
~ View preview_selected_color
# void onCreate(Bundle)
+ void onRequestPermissionsResult(int,String[],int[])
+ void saveImage()
+ void onBackPressed()
}
class com.example.wetouriah.TaskAssignmentChecker {
}
class com.example.wetouriah.DriversLicense {
~ String id
+ String getId()
+ void setId(String)
+ String getLicense_owner()
+ void setLicense_owner(String)
+ String getFullname()
+ void setFullname(String)
+ String getIdentity_number()
+ void setIdentity_number(String)
+ String getDate_of_birth()
+ void setDate_of_birth(String)
+ String getLicense_number()
+ void setLicense_number(String)
+ String getExpiry_date()
+ void setExpiry_date(String)
+ String getCountry_of_issue()
+ void setCountry_of_issue(String)
+ String getCode()
+ void setCode(String)
+ String getRestrictions()
+ void setRestrictions(String)
+ String getGender()
+ void setGender(String)
+ String getDate_of_issue()
+ void setDate_of_issue(String)
+ String getUploadLicense()
+ void setUploadLicense(String)
+ String getIs_approved()
+ void setIs_approved(String)
}
class com.example.wetouriah.DriverPortal {
~ Button btnProfile
- DrawerLayout drawerLayout
- ActionBarDrawerToggle toggle
- NavigationView navigationView
~ TextView headerUsername
- TabLayout tab_layout
- RelativeLayout lyAllUndelivered
- Handler handler
- Runnable runnable
+ {static} String NEXT_SCREEN
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
+ boolean onNavigationItemSelected(MenuItem)
+ void onBackPressed()
- void showToast(String)
- void Logout()
- void createNotification(PickUpRequestItem)
- void startPeriodicApiCall()
}
class com.example.wetouriah.History {
# void onCreate(Bundle)
}
class com.example.wetouriah.MessagesResponse {
- Integer id
- String message
- String timestamp
- Integer pickup
- Integer sender
+ Integer getId()
+ void setId(Integer)
+ String getMessage()
+ void setMessage(String)
+ String getTimestamp()
+ void setTimestamp(String)
+ Integer getPickup()
+ void setPickup(Integer)
+ Integer getSender()
+ void setSender(Integer)
}
class com.example.wetouriah.AuthenticatedUser {
- String username
- String role
- String id
+ String getUsername()
+ void setUsername(String)
+ String getRole()
+ void setRole(String)
+ String getID()
+ void setID(String)
}
class com.example.wetouriah.AdminPortal {
~ RelativeLayout lyAllusers
- DrawerLayout drawerLayout
- ActionBarDrawerToggle toggle
- NavigationView navigationView
~ TextView headerUsername
# void onCreate(Bundle)
+ void mGetAllUsers()
+ void mGetAllCars()
+ void mGetAllDriversLicense()
+ void mGetAllWarehouses()
+ boolean onOptionsItemSelected(MenuItem)
+ boolean onNavigationItemSelected(MenuItem)
+ void hideAlllayers()
+ void DriversLicense()
+ void changePassword()
+ void onBackPressed()
- void showToast(String)
- void Logout()
}
class com.example.wetouriah.AdapterAllCars {
~ Context context
~ List<CarItem> CarItems
- OnClickListener onClickListener
+ AllCarsViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(AllCarsViewHolder,int)
+ int getItemCount()
+ void setOnClickListener(OnClickListener)
}
interface com.example.wetouriah.AdapterAllCars$OnClickListener {
~ void onClick(int,CarItem)
}
class com.example.wetouriah.AdapterPickUpRequest {
~ Context context
~ List<PickUpRequestItem> pickUpRequestItems
- OnClickListener onClickListener
+ PickUpRequestViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(PickUpRequestViewHolder,int)
+ int getItemCount()
+ void setOnClickListener(OnClickListener)
}
interface com.example.wetouriah.AdapterPickUpRequest$OnClickListener {
~ void onClick(int,PickUpRequestItem)
}
class com.example.wetouriah.PickUpRequestDetailed {
~ TextView request_time
~ TextView recipient_name
~ Button drive
~ RadioGroup rdgAcceptDecline
~ RadioButton rdAccept
~ RelativeLayout lyMainDetailed
~ Button btnRate
~ PickUpRequestItem pickUpRequestItem
~ String pickup
~ SharedPreferences sharedPreferences
~ String role
~ Button btnSign
+ {static} String NEXT_SCREEN
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
+ void GetAnID(String)
+ {static} void openGoogleMapsDirections(Context,String,String)
- {static} LatLng geocodeAddress(Context,String)
+ void mAcceptDecline(String,String)
+ boolean onCreateOptionsMenu(Menu)
}
class com.example.wetouriah.AddUserResponse {
- Boolean success
- Integer statusCode
- String message
+ Boolean getSuccess()
+ void setSuccess(Boolean)
+ Integer getStatusCode()
+ void setStatusCode(Integer)
+ String getMessage()
+ void setMessage(String)
}
class com.example.wetouriah.AdapterAllWarehouses {
~ Context context
~ List<WareHouseItemAdmin> wareHouseItemAdmins
- OnClickListener onClickListener
+ AllWarehousesViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(AllWarehousesViewHolder,int)
+ int getItemCount()
+ void setOnClickListener(OnClickListener)
}
interface com.example.wetouriah.AdapterAllWarehouses$OnClickListener {
~ void onClick(int,WareHouseItemAdmin)
}
class com.example.wetouriah.DirectionParser {
+ List<List<HashMap<String,String>>> parse(JSONObject)
- List<LatLng> decodePoly(String)
}
class com.example.wetouriah.APIResponse {
- Boolean success
- Integer statusCode
- String message
+ Boolean getSuccess()
+ void setSuccess(Boolean)
+ Integer getStatusCode()
+ void setStatusCode(Integer)
+ String getMessage()
+ void setMessage(String)
}
class com.example.wetouriah.AddCar {
~ EditText car_owner
~ CheckBox is_approved
~ Button btnAddCar
- APIService apiService
~ String user_id
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
- void addCar(CarItem)
- void mupdateCar(CarItem)
+ void loadCar(String)
+ void add_updateCar(String,String)
}
class com.example.wetouriah.WarehouseResponse {
- Integer id
- String image
- String address
- String volume
- Boolean cctv
- Boolean armedResponse
- Boolean fireSafetyAndManagement
- Boolean parkingSpace
- String operatingHours
- Boolean isApproved
- Integer warehouseOwner
+ Integer getId()
+ void setId(Integer)
+ String getImage()
+ void setImage(String)
+ String getAddress()
+ void setAddress(String)
+ String getVolume()
+ void setVolume(String)
+ Boolean getCctv()
+ void setCctv(Boolean)
+ Boolean getArmedResponse()
+ void setArmedResponse(Boolean)
+ Boolean getFireSafetyAndManagement()
+ void setFireSafetyAndManagement(Boolean)
+ Boolean getParkingSpace()
+ void setParkingSpace(Boolean)
+ String getOperatingHours()
+ void setOperatingHours(String)
+ Boolean getIsApproved()
+ void setIsApproved(Boolean)
+ Integer getWarehouseOwner()
+ void setWarehouseOwner(Integer)
}
class com.example.wetouriah.Login {
~ EditText edtUsername
~ Button btnButton
~ TextView btnResetPassword
# void onCreate(Bundle)
+ void mLogin(String,String)
+ void changePassword()
+ void onBackPressed()
}
class com.example.wetouriah.AllWarehousesViewHolder {
~ ImageView image
~ TextView address
~ CheckBox cctv
}
class com.example.wetouriah.UserItem {
~ String id
+ String getId()
+ void setId(String)
+ String getUsername()
+ void setUsername(String)
+ String getAddress()
+ void setAddress(String)
+ String getFirst_name()
+ void setFirst_name(String)
+ String getLast_name()
+ void setLast_name(String)
+ String getEmail()
+ void setEmail(String)
+ String getIs_active()
+ void setIs_active(String)
+ String getProfile_picture()
+ void setProfile_picture(String)
+ String getRole()
+ void setRole(String)
+ String getPhone_number()
+ void setPhone_number(String)
}
interface com.example.wetouriah.APIService {
~ Call<AddUserResponse> addUser(RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,MultipartBody.Part,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<APIResponse> updateUser(RequestBody,RequestBody,RequestBody,MultipartBody.Part,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<LoginResponse> loginUser(RequestBody,RequestBody)
~ Call<WarehouseResponse> getWarehouse(RequestBody)
~ Call<APIResponse> addWarehouse(RequestBody,MultipartBody.Part,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<APIResponse> updateWarehouse(RequestBody,RequestBody,MultipartBody.Part,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<APIResponse> updateWarehouseNoImage(RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<APIResponse> addPickRequest(RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<ImageResponse> getImage(RequestBody)
~ Call<CarResponse> addCar(RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<CarResponse> updateCar(RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<DriversLicenseResponse> addDriversLicense(RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<DriversLicenseResponse> updateDriversLicense(RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody,RequestBody)
~ Call<CarResponse> loadCar(RequestBody)
~ Call<DriversLicenseResponse> loadDriversLicense(RequestBody)
~ Call<PickupResponse> getPickUp(RequestBody)
~ Call<List<WarehouseResponse>> getWarehousesObjects(String)
~ Call<GetUserReponse> loadUser(RequestBody)
~ Call<APIResponse> rate(RequestBody,RequestBody)
~ Call<APIResponse> sendMessage(RequestBody,RequestBody,RequestBody)
~ Call<List<MessagesResponse>> getMessageObjects(RequestBody)
~ Call<List<AllUsersResponse>> getAllUSerObjects()
~ Call<List<CarResponse>> getAllCarObjects()
~ Call<List<WarehouseResponse>> getAllWareHouseObjects()
~ Call<List<DriversLicenseResponse>> getAllDriversLicenseObjects()
~ Call<APIResponse> updateWarehouseApproval(RequestBody,RequestBody,RequestBody)
~ Call<APIResponse> updateCarApproval(RequestBody,RequestBody)
~ Call<APIResponse> updateLicenseApproval(RequestBody,RequestBody)
~ Call<APIResponse> updateUserActive(RequestBody,RequestBody)
~ Call<List<RequestPickupResponse>> getPickupRequest(RequestBody,RequestBody,RequestBody)
~ Call<List<RequestPickupResponse>> getAllUserRequest(RequestBody)
~ Call<List<RequestPickupResponse>> getUnDeliveredObjects(RequestBody)
~ Call<List<RequestPickupResponse>> getUnRatedObjects(RequestBody)
~ Call<PickupResponse> getPickupIDfromRequestpickup(RequestBody)
~ Call<List<RequestPickupResponse>> getUnDeliveredDriverObjects(RequestBody)
~ Call<List<RequestPickupResponse>> getUnRatedDriverObjects(RequestBody)
~ Call<List<RequestPickupResponse>> getAllDriverObjects(RequestBody)
~ Call<RequestPickupResponse> checkTaskAssignment(RequestBody)
~ Call<APIResponse> acceptDeclineJob(RequestBody,RequestBody)
~ Call<APIResponse> uploadProofImage(RequestBody,MultipartBody.Part)
~ Call<APIResponse> setIsDelivered(RequestBody)
~ Call<DeliveryImagesAndRatingResponse> getImagesAndRating(RequestBody)
}
class com.example.wetouriah.TitleOnAmap {
~ GoogleMap mMap
- List<WareHouseItem> items
- List<String> warehouseAddresses
- List<String> houseAddresses
# void onCreate(Bundle)
+ void onMapReady(GoogleMap)
- LatLng getLocationFromAddress(String)
- void createHouseAddresses()
- void processAddresses(List<String>)
+ void onBackPressed()
}
class com.example.wetouriah.AddDriversLicense {
~ EditText license_owner
~ CheckBox is_approved
- APIService apiService
~ Button btnAddDriversLicense
~ String user_id
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
- void addDriversLicense(DriversLicense)
- void mupdateCar(DriversLicense)
+ void loadDriversLicense(String)
+ void add_updateDriversLicense(String,String)
}
class com.example.wetouriah.AdapterWarehouse {
~ Context context
~ List<WareHouseItem> items
+ ViewHolderWarehouse onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolderWarehouse,int)
+ int getItemCount()
}
class com.example.wetouriah.AllDriversLicenseViewHolder {
~ TextView id
~ CheckBox is_approved
}
class com.example.wetouriah.Constants {
+ {static} String SERVER_IP_ADDRESS
}
class com.example.wetouriah.RealPathUtil {
+ {static} String getRealPath(Context,Uri)
+ {static} String getRealPathFromURI_API11to18(Context,Uri)
+ {static} String getRealPathFromURI_BelowAPI11(Context,Uri)
+ {static} String getRealPathFromURI_API19(Context,Uri)
+ {static} String getDataColumn(Context,Uri,String,String[])
+ {static} boolean isExternalStorageDocument(Uri)
+ {static} boolean isDownloadsDocument(Uri)
+ {static} boolean isMediaDocument(Uri)
+ {static} boolean isGooglePhotosUri(Uri)
}
class com.example.wetouriah.PickupResponse {
- Integer id
- String startDatetime
- String endDatetime
- Object duration
- Object tip
- Object rating
- String lastKnownLocation
- Boolean isDelivered
- Integer requestPickup
- Integer car
+ Integer getId()
+ void setId(Integer)
+ String getStartDatetime()
+ void setStartDatetime(String)
+ String getEndDatetime()
+ void setEndDatetime(String)
+ Object getDuration()
+ void setDuration(Object)
+ Object getTip()
+ void setTip(Object)
+ Object getRating()
+ void setRating(Object)
+ String getLastKnownLocation()
+ void setLastKnownLocation(String)
+ Boolean getIsDelivered()
+ void setIsDelivered(Boolean)
+ Integer getRequestPickup()
+ void setRequestPickup(Integer)
+ Integer getCar()
+ void setCar(Integer)
}
class com.example.wetouriah.CarItem {
- String id
- String car_owner
- String type
- String capacity
- String color
- String make
- String model
- String year
- String license_plate
- String is_approved
+ String getIs_approved()
+ void setIs_approved(String)
+ String getId()
+ void setId(String)
+ String getCar_owner()
+ void setCar_owner(String)
+ String getType()
+ void setType(String)
+ String getCapacity()
+ void setCapacity(String)
+ String getColor()
+ void setColor(String)
+ String getMake()
+ void setMake(String)
+ String getModel()
+ void setModel(String)
+ String getYear()
+ void setYear(String)
+ String getLicense_plate()
+ void setLicense_plate(String)
}
class com.example.wetouriah.AllUsersViewHolder {
~ ImageView profile_picture
~ CheckBox is_active
~ TextView username
}
class com.example.wetouriah.CustomerPortal {
- DrawerLayout drawerLayout
- ActionBarDrawerToggle toggle
- NavigationView navigationView
- RelativeLayout lyPickRequestList
- RelativeLayout lyLocationsWightVolume
~ EditText pickdateEditText
~ EditText recipient_name
~ Button btnAddPickRequest
- int year
~ FloatingActionButton mAddFab
~ ScrollView lyAddPickRequest
~ TextView headerUsername
~ TextView txtPrice
- Handler handler
- Runnable runnable
+ {static} String NEXT_SCREEN
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
+ boolean onNavigationItemSelected(MenuItem)
+ void onBackPressed()
- void hideAllLayers()
- void showToast(String)
- void Logout()
- void showDatePicker(EditText)
- void showTimePicker(EditText)
+ void mAddpickRequest(String,String,String,String,String,String,String,String,String)
+ void mGetAllPickRequest()
+ double mCalulatePrice(double,double,double)
- void startPeriodicApiCall()
- void createNotification()
+ void changePassword()
}
class com.example.wetouriah.AdapterAllDriversLicense {
~ Context context
~ List<DriversLicense> DriversLicenses
- OnClickListener onClickListener
+ AllDriversLicenseViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(AllDriversLicenseViewHolder,int)
+ int getItemCount()
+ void setOnClickListener(OnClickListener)
}
interface com.example.wetouriah.AdapterAllDriversLicense$OnClickListener {
~ void onClick(int,DriversLicense)
}
class com.example.wetouriah.CarResponse {
- Integer id
- String type
- String capacity
- String color
- String make
- String model
- String year
- String licensePlate
- Boolean isApproved
- Integer carOwner
+ Integer getId()
+ void setId(Integer)
+ String getType()
+ void setType(String)
+ String getCapacity()
+ void setCapacity(String)
+ String getColor()
+ void setColor(String)
+ String getMake()
+ void setMake(String)
+ String getModel()
+ void setModel(String)
+ String getYear()
+ void setYear(String)
+ String getLicensePlate()
+ void setLicensePlate(String)
+ Boolean getIsApproved()
+ void setIsApproved(Boolean)
+ Integer getCarOwner()
+ void setCarOwner(Integer)
}
class com.example.wetouriah.LoginResponse {
- Boolean success
- Integer statusCode
- String message
- String access
- String refresh
- AuthenticatedUser authenticatedUser
+ Boolean getSuccess()
+ void setSuccess(Boolean)
+ Integer getStatusCode()
+ void setStatusCode(Integer)
+ String getMessage()
+ void setMessage(String)
+ String getAccess()
+ void setAccess(String)
+ String getRefresh()
+ void setRefresh(String)
+ AuthenticatedUser getAuthenticatedUser()
+ void setAuthenticatedUser(AuthenticatedUser)
}
class com.example.wetouriah.AllUsersResponse {
- Integer id
- String password
- Object lastLogin
- Boolean isSuperuser
- String username
- String firstName
- String lastName
- String email
- Boolean isStaff
- Boolean isActive
- String dateJoined
- String profilePicture
- Integer role
- String title
- String firstname
- String lastname
- String address
- String phoneNumber
- List<Object> groups
- List<Object> userPermissions
+ Integer getId()
+ void setId(Integer)
+ String getPassword()
+ void setPassword(String)
+ Object getLastLogin()
+ void setLastLogin(Object)
+ Boolean getIsSuperuser()
+ void setIsSuperuser(Boolean)
+ String getUsername()
+ void setUsername(String)
+ String getFirstName()
+ void setFirstName(String)
+ String getLastName()
+ void setLastName(String)
+ String getEmail()
+ void setEmail(String)
+ Boolean getIsStaff()
+ void setIsStaff(Boolean)
+ Boolean getIsActive()
+ void setIsActive(Boolean)
+ String getDateJoined()
+ void setDateJoined(String)
+ String getProfilePicture()
+ void setProfilePicture(String)
+ Integer getRole()
+ void setRole(Integer)
+ String getTitle()
+ void setTitle(String)
+ String getFirstname()
+ void setFirstname(String)
+ String getLastname()
+ void setLastname(String)
+ String getAddress()
+ void setAddress(String)
+ String getPhoneNumber()
+ void setPhoneNumber(String)
+ List<Object> getGroups()
+ void setGroups(List<Object>)
+ List<Object> getUserPermissions()
+ void setUserPermissions(List<Object>)
}
class com.example.wetouriah.Profile {
- ImageView imageView
- EditText email
- Button selectImageButton
- String imagepath
- CheckBox status
~ String user_id
# void onCreate(Bundle)
+ void updateUserStatus(String,String)
# void onActivityResult(int,int,Intent)
+ boolean onOptionsItemSelected(MenuItem)
+ void updateUser(String,String,String,String,String,String,String)
+ void loadUser(String)
}
class com.example.wetouriah.MessageViewHolder {
~ TextView message
}
class com.example.wetouriah.MainActivity {
~ Button btnLogin
# void onCreate(Bundle)
# void onResume()
# void onPause()
# void onDestroy()
}
class com.example.wetouriah.RequestPickupResponse {
- Integer id
- String trackingNumber
- String requestTime
- String dateAndTimePickup
- String recipientName
- String recipientPhone
- Object pickupLocation
- Object dropoffLocation
- Object volume
- String weight
- Object priceToPay
- Integer status
- Integer customer
- List<Integer> images
+ Integer getId()
+ void setId(Integer)
+ String getTrackingNumber()
+ void setTrackingNumber(String)
+ String getRequestTime()
+ void setRequestTime(String)
+ String getDateAndTimePickup()
+ void setDateAndTimePickup(String)
+ String getRecipientName()
+ void setRecipientName(String)
+ String getRecipientPhone()
+ void setRecipientPhone(String)
+ Object getPickupLocation()
+ void setPickupLocation(Object)
+ Object getDropoffLocation()
+ void setDropoffLocation(Object)
+ Object getVolume()
+ void setVolume(Object)
+ String getWeight()
+ void setWeight(String)
+ Object getPriceToPay()
+ void setPriceToPay(Object)
+ Integer getStatus()
+ void setStatus(Integer)
+ Integer getCustomer()
+ void setCustomer(Integer)
+ List<Integer> getImages()
+ void setImages(List<Integer>)
}
class com.example.wetouriah.Chat {
~ EditText edtmessage
~ Button btnSend
~ String pickup
# void onCreate(Bundle)
+ void sendMessage(String,String,String)
+ void mGetMessages(String)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.wetouriah.MessageItem {
~ String id
~ String message
~ String timestamp
~ String pickup
~ String sender
+ String getId()
+ void setId(String)
+ String getMessage()
+ void setMessage(String)
+ String getTimestamp()
+ void setTimestamp(String)
+ String getPickup()
+ void setPickup(String)
+ String getSender()
+ void setSender(String)
}
class com.example.wetouriah.AdapterMessage {
~ Context context
~ List<MessageItem> messageItems
+ MessageViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(MessageViewHolder,int)
+ int getItemCount()
}
class com.example.wetouriah.PickUpRequestViewHolder {
~ TextView tracking_number
}
class com.example.wetouriah.GetUserReponse {
- Integer id
- String password
- Object lastLogin
- Boolean isSuperuser
- String username
- String firstName
- String lastName
- String email
- Boolean isStaff
- Boolean isActive
- String dateJoined
- String profilePicture
- Integer role
- String title
- String firstname
- String lastname
- String address
- String phoneNumber
- List<Object> groups
- List<Object> userPermissions
+ Integer getId()
+ void setId(Integer)
+ String getPassword()
+ void setPassword(String)
+ Object getLastLogin()
+ void setLastLogin(Object)
+ Boolean getIsSuperuser()
+ void setIsSuperuser(Boolean)
+ String getUsername()
+ void setUsername(String)
+ String getFirstName()
+ void setFirstName(String)
+ String getLastName()
+ void setLastName(String)
+ String getEmail()
+ void setEmail(String)
+ Boolean getIsStaff()
+ void setIsStaff(Boolean)
+ Boolean getIsActive()
+ void setIsActive(Boolean)
+ String getDateJoined()
+ void setDateJoined(String)
+ String getProfilePicture()
+ void setProfilePicture(String)
+ Integer getRole()
+ void setRole(Integer)
+ String getTitle()
+ void setTitle(String)
+ String getFirstname()
+ void setFirstname(String)
+ String getLastname()
+ void setLastname(String)
+ String getAddress()
+ void setAddress(String)
+ String getPhoneNumber()
+ void setPhoneNumber(String)
+ List<Object> getGroups()
+ void setGroups(List<Object>)
+ List<Object> getUserPermissions()
+ void setUserPermissions(List<Object>)
}
class com.example.wetouriah.AdapterLocations {
~ Context context
~ List<LocationsItem> locationsItems
- OnClickListener onClickListener
+ LocationsViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(LocationsViewHolder,int)
+ int getItemCount()
+ void setOnClickListener(OnClickListener)
}
interface com.example.wetouriah.AdapterLocations$OnClickListener {
~ void onClick(int,LocationsItem)
}
class com.example.wetouriah.DriversLicenseResponse {
- Integer id
- String fullname
- String identityNumber
- String dateOfBirth
- Object licenseNumber
- String expiryDate
- String countryOfIssue
- String code
- String restrictions
- String gender
- String dateOfIssue
- String uploadLicense
- Boolean isApproved
- Integer licenseOwner
+ Integer getId()
+ void setId(Integer)
+ String getFullname()
+ void setFullname(String)
+ String getIdentityNumber()
+ void setIdentityNumber(String)
+ String getDateOfBirth()
+ void setDateOfBirth(String)
+ Object getLicenseNumber()
+ void setLicenseNumber(Object)
+ String getExpiryDate()
+ void setExpiryDate(String)
+ String getCountryOfIssue()
+ void setCountryOfIssue(String)
+ String getCode()
+ void setCode(String)
+ String getRestrictions()
+ void setRestrictions(String)
+ String getGender()
+ void setGender(String)
+ String getDateOfIssue()
+ void setDateOfIssue(String)
+ String getUploadLicense()
+ void setUploadLicense(String)
+ Boolean getIsApproved()
+ void setIsApproved(Boolean)
+ Integer getLicenseOwner()
+ void setLicenseOwner(Integer)
}
class com.example.wetouriah.User {
# void onCreate(Bundle)
}
class com.example.wetouriah.DeliveryImagesAndRatingResponse {
- List<String> images
- Integer rating
+ List<String> getImages()
+ void setImages(List<String>)
+ Integer getRating()
+ void setRating(Integer)
}
class com.example.wetouriah.LocationsItem {
~ String location
~ String timestamp
~ String status
+ String getLocation()
+ void setLocation(String)
+ String getTimestamp()
+ void setTimestamp(String)
+ String getStatus()
+ void setStatus(String)
}
class com.example.wetouriah.ResetPassword {
~ TextView btnlogin
~ Button btnResetButton
~ LinearLayout lyEnterUsername
~ TextInputEditText edtUsername
~ String receivedData
# void onCreate(Bundle)
+ void onBackPressed()
}
class com.example.wetouriah.LocationsViewHolder {
~ TextView location
}
class com.example.wetouriah.AddWarehouse {
~ String warehouse_owner
- String imagepath
~ ImageView image
~ EditText address
~ CheckBox cctv
~ Button btnAddWarehouse
- {static} String TAG
~ String user_id
# void onCreate(Bundle)
# void onActivityResult(int,int,Intent)
+ boolean onOptionsItemSelected(MenuItem)
+ void add_updateWarehouse(int,String,String,String,String,String,String,String,String)
+ void add_updateWarehouseNoImage(int,String,String,String,String,String,String,String,String)
+ void loadwarehouse(String)
+ void add_updateWarehouse(String,String,String)
}
class com.example.wetouriah.WareHouseItem {
~ String address
+ String getAddress()
+ void setAddress(String)
}


com.example.wetouriah.ViewHolder <|-- com.example.wetouriah.ViewHolderWarehouse
java.io.Serializable <|.. com.example.wetouriah.WareHouseItemAdmin
com.example.wetouriah.Adapter <|-- com.example.wetouriah.AdapterAllUsers
com.example.wetouriah.AdapterAllUsers +.. com.example.wetouriah.AdapterAllUsers$OnClickListener
com.example.wetouriah.OnNavigationItemSelectedListener <|.. com.example.wetouriah.WarehousePortal
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.WarehousePortal
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.TrackParcel
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.Deliver
java.io.Serializable <|.. com.example.wetouriah.PickUpRequestItem
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.Register
com.example.wetouriah.ViewHolder <|-- com.example.wetouriah.AllCarsViewHolder
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.Signature
java.io.Serializable <|.. com.example.wetouriah.DriversLicense
com.example.wetouriah.OnNavigationItemSelectedListener <|.. com.example.wetouriah.DriverPortal
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.DriverPortal
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.History
com.example.wetouriah.OnNavigationItemSelectedListener <|.. com.example.wetouriah.AdminPortal
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.AdminPortal
com.example.wetouriah.Adapter <|-- com.example.wetouriah.AdapterAllCars
com.example.wetouriah.AdapterAllCars +.. com.example.wetouriah.AdapterAllCars$OnClickListener
com.example.wetouriah.Adapter <|-- com.example.wetouriah.AdapterPickUpRequest
com.example.wetouriah.AdapterPickUpRequest +.. com.example.wetouriah.AdapterPickUpRequest$OnClickListener
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.PickUpRequestDetailed
com.example.wetouriah.Adapter <|-- com.example.wetouriah.AdapterAllWarehouses
com.example.wetouriah.AdapterAllWarehouses +.. com.example.wetouriah.AdapterAllWarehouses$OnClickListener
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.AddCar
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.Login
com.example.wetouriah.ViewHolder <|-- com.example.wetouriah.AllWarehousesViewHolder
java.io.Serializable <|.. com.example.wetouriah.UserItem
com.google.android.gms.maps.OnMapReadyCallback <|.. com.example.wetouriah.TitleOnAmap
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.TitleOnAmap
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.AddDriversLicense
com.example.wetouriah.Adapter <|-- com.example.wetouriah.AdapterWarehouse
com.example.wetouriah.ViewHolder <|-- com.example.wetouriah.AllDriversLicenseViewHolder
java.io.Serializable <|.. com.example.wetouriah.CarItem
com.example.wetouriah.ViewHolder <|-- com.example.wetouriah.AllUsersViewHolder
com.example.wetouriah.OnNavigationItemSelectedListener <|.. com.example.wetouriah.CustomerPortal
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.CustomerPortal
com.example.wetouriah.Adapter <|-- com.example.wetouriah.AdapterAllDriversLicense
com.example.wetouriah.AdapterAllDriversLicense +.. com.example.wetouriah.AdapterAllDriversLicense$OnClickListener
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.Profile
com.example.wetouriah.ViewHolder <|-- com.example.wetouriah.MessageViewHolder
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.Chat
java.io.Serializable <|.. com.example.wetouriah.MessageItem
com.example.wetouriah.Adapter <|-- com.example.wetouriah.AdapterMessage
com.example.wetouriah.ViewHolder <|-- com.example.wetouriah.PickUpRequestViewHolder
com.example.wetouriah.Adapter <|-- com.example.wetouriah.AdapterLocations
com.example.wetouriah.AdapterLocations +.. com.example.wetouriah.AdapterLocations$OnClickListener
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.User
java.io.Serializable <|.. com.example.wetouriah.LocationsItem
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.ResetPassword
com.example.wetouriah.ViewHolder <|-- com.example.wetouriah.LocationsViewHolder
androidx.appcompat.app.AppCompatActivity <|-- com.example.wetouriah.AddWarehouse
@enduml