# Generated by Django 4.2.1 on 2023-08-15 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='driver_license',
        ),
        migrations.CreateModel(
            name='DriversLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('country_of_issue', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('restrictions', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('drivers_license_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_issue', models.DateTimeField(blank=True, null=True)),
                ('uploadLicense', models.ImageField(blank=True, default='NoImage.jpg', null=True, upload_to='')),
                ('is_approved', models.BooleanField(default=False)),
                ('license_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
