# Generated by Django 4.2.1 on 2023-07-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestpickup",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "driver_assigned"),
                    (2, "picked_up"),
                    (3, "in_transit"),
                    (4, "out_for_delivery"),
                    (5, "delivered"),
                    (6, "returned"),
                ],
                default=4,
                null=True,
            ),
        ),
    ]
