# Generated by Django 4.2.1 on 2023-06-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_car_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
