# Generated by Django 4.2.1 on 2023-07-28 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_requestpickup_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestpickup",
            name="date_and_time_dropoff",
        ),
        migrations.RemoveField(
            model_name="requestpickup",
            name="parcel_description",
        ),
        migrations.RemoveField(
            model_name="requestpickup",
            name="special_notes",
        ),
        migrations.RemoveField(
            model_name="requestpickup",
            name="updated",
        ),
    ]
