# Generated by Django 4.2.1 on 2023-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_status_requestpickupstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpickup',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestpickup',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
