# Generated by Django 4.2.1 on 2023-06-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_warehouse_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='last_known_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
