# Generated by Django 4.2.1 on 2023-05-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_requestpickup_dropoff_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPickupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('requestpickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.requestpickup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile')),
            ],
        ),
    ]
