# Generated by Django 4.2.1 on 2023-09-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_requestpickup_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglog',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.requestpickupstatus'),
        ),
        migrations.AlterField(
            model_name='requestpickup',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
