# Generated by Django 4.2.1 on 2023-05-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_requestpickupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpickup',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
    ]
