# Generated by Django 4.2.1 on 2023-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_requestpickup_is_picked'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPickupImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_pickup_images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='requestpickup',
            name='images',
            field=models.ManyToManyField(to='base.requestpickupimages'),
        ),
    ]
