# Generated by Django 4.2.1 on 2023-05-24 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_requestpickupimages_requestpickup_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='last_known_location',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
