# Generated by Django 4.2.1 on 2023-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_proofofdelivery_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
