# Generated by Django 4.2.1 on 2023-10-11 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_remove_driverslicense_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DriverAvailability",
            new_name="CourierAvailability",
        ),
        migrations.RenameField(
            model_name="courieravailability",
            old_name="driver",
            new_name="courier",
        ),
        migrations.RemoveField(
            model_name="requestpickup",
            name="car",
        ),
        migrations.AddField(
            model_name="requestpickup",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
