# Generated by Django 4.2.1 on 2023-10-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_trackinglog_estimated_arrival_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courieravailability",
            name="distance_to_pickup",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
