# Generated by Django 4.2.1 on 2023-10-12 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_courieravailability_distance_to_pickup"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclineList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requestPickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.requestpickup",
                    ),
                ),
            ],
        ),
    ]
